import { Event } from '../types';

export const seedEvents: Omit<Event, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'Tech Innovation Summit 2026',
    description: 'Join us for a day of cutting-edge technology discussions, networking, and innovation. Featuring keynote speakers from leading tech companies and hands-on workshops.',
    date: '2026-04-15',
    startTime: '09:00',
    endTime: '17:00',
    venue: 'Convention Center, Hall A',
    venueLink: 'https://maps.google.com',
    category: 'Technology',
    capacity: 200,
    registrationDeadline: '2026-04-10',
    status: 'published',
  },
  {
    title: 'Web Development Workshop',
    description: 'A comprehensive workshop covering modern web development practices, including React, TypeScript, and backend integration. Perfect for intermediate developers.',
    date: '2026-04-20',
    startTime: '10:00',
    endTime: '16:00',
    venue: 'Tech Hub Building, Room 301',
    category: 'Workshop',
    capacity: 50,
    registrationDeadline: '2026-04-17',
    status: 'published',
  },
  {
    title: 'Annual Hackathon 2026',
    description: '48-hour hackathon focused on solving real-world problems with technology. Form teams, code, and compete for amazing prizes!',
    date: '2026-05-10',
    startTime: '18:00',
    endTime: '18:00',
    venue: 'Innovation Lab, Building B',
    venueLink: 'https://maps.google.com',
    category: 'Hackathon',
    capacity: 150,
    registrationDeadline: '2026-05-05',
    status: 'published',
  },
  {
    title: 'AI & Machine Learning Conference',
    description: 'Explore the latest advancements in artificial intelligence and machine learning. Network with researchers, practitioners, and industry leaders.',
    date: '2026-05-25',
    startTime: '09:00',
    endTime: '18:00',
    venue: 'Grand Auditorium',
    category: 'Conference',
    capacity: 300,
    registrationDeadline: '2026-05-20',
    status: 'published',
  },
  {
    title: 'Startup Pitch Night',
    description: 'Watch innovative startups pitch their ideas to a panel of investors and industry experts. Networking session to follow.',
    date: '2026-04-30',
    startTime: '18:00',
    endTime: '21:00',
    venue: 'Startup Hub, Main Stage',
    category: 'Networking',
    capacity: 100,
    registrationDeadline: '2026-04-27',
    status: 'published',
  },
  {
    title: 'Data Science Bootcamp',
    description: 'Intensive 3-day bootcamp covering data analysis, visualization, and machine learning fundamentals using Python and popular libraries.',
    date: '2026-06-05',
    startTime: '09:00',
    endTime: '17:00',
    venue: 'Learning Center, Rooms 201-203',
    category: 'Workshop',
    capacity: 40,
    registrationDeadline: '2026-06-01',
    status: 'published',
  },
];
